### ISSUE TITLE
Optional type used to indicate default values

### ISSUE THREAD

**Issue by MichelBartels** [deepset-ai/canals#105]
Bug description
----------------
I would expect the following code to work:
```py
from canals import Pipeline, component

@component
class A:
    @component.output_types(b=int)
    def run(self, a: int, b: int = 0):
        return {"c": 4}
    def to_dict(self):
        pass
    @classmethod
    def from_dict(cls, _):
        pass

pipeline = Pipeline()
pipeline.add_component("a", A())
print(pipeline.run({"a": {"a": 0}}))
```
However, a `ValueError` is raised:
```
Traceback (most recent call last):
  File "<...>", line 16, in <module>
    print(pipeline.run({"a": {"a": 0}}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>/canals/pipeline/pipeline.py", line 415, in run
    data = _validate_pipeline_input(self.graph, input_values=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>/canals/pipeline/validation.py", line 52, in _validate_pipeline_input
    _validate_input_sockets_are_connected(graph, input_values)
  File "<...>/canals/pipeline/validation.py", line 75, in _validate_input_sockets_are_connected
    raise ValueError(f"Missing input: {node}.{socket.name}")
ValueError: Missing input: a.b
```
I can annotate b as `Optional` to make it work:
```py
from typing import Optional
from canals import Pipeline, component

@component
class A:
    @component.output_types(b=int)
    def run(self, a: int, b: Optional[int] = 0):
        return {"c": 4}
    def to_dict(self):
        pass
    @classmethod
    def from_dict(cls, _):
        pass

pipeline = Pipeline()
pipeline.add_component("a", A())
print(pipeline.run({"a": {"a": 0}}))
```

However, this does not have the same meaning. [The Python documentation says](https://docs.python.org/3/library/typing.html#typing.Optional):
> `Optional[X]` is equivalent to `X | None` (or `Union[X, None]`).
> 
> Note that this is not the same concept as an optional argument, which is one that has a default.

The naming of this type is a bit confusing because it does not have anything to do with optional parameters and it's more like an `option` type in languages like OCaml, Rust, Java etc.
In my example, this would mean that `None` is a valid value for `b` which you would not always want.

The bug also exists in the reverse case although it's probably less likely to occur. You can see this in the following somewhat realistic example which implements a NAND components using three valued logic like you might find in SQL:
```py
from typing import Optional
from canals import Pipeline, component

@component
class ThreeValuedNAND:
    @component.output_types(y=bool)
    def run(self, a: Optional[bool], b: Optional[bool]):
        if a == False or b == False:
            return True
        if a and b:
            return False
        return None
    def to_dict(self):
        pass
    @classmethod
    def from_dict(cls, _):
        pass

pipeline = Pipeline()
pipeline.add_component("nand", ThreeValuedNAND())
print(pipeline.run({"nand": {"a": True}}))
```
The validation does not catch that I haven't provided `b` because it considers the `b` socket to be optional. This might also have further consequences with more complicated pipelines because it does not wait for input, but I haven't investigated that.

Fix
---
[This line](https://github.com/deepset-ai/canals/blob/68c1aedf4d1e173d4718fb00a07d8eec06f6db71/canals/component/component.py#L154) should not check the type, but should rather check if a default value is provided. It might also make sense to call the key `has_default` instead of `is_optional`.

**Comment by ZanSara** [comment]
Thank you for the investigation! So, I blame half of this issue on our design choices and half on lacking documentation.

The problem is the following: we need a way to tell Canals which inputs need to be waited for, and which ones do not. This has to be possible regardless of whether the input has a default set in the `run()` signature, because there are cases where setting a default is not possible (or quite awkward). So we cannot (or better, prefer not to) rely on the presence of a default value to understand whether an input needs to be waited for or not.

We then decided to use the typing to communicate this distinction (this is where I blame the lack of documentation): `Optional` parameters are NOT waited for, while all other are waited for, regardless of whether a default is set or not.

However (and here I blame our design choices) you're right that we're hijacking `Optional` and changing its semantic in a way that a Python developer can find very surprising as soon as they meet with a situation like yours.

On the other hand, I don't like the idea of using the default to check if a parameter is mandatory or not, because right now it can't be enforced consistently. Using only `Optional` at least provides some consistency, for as awkward as it is: checking also the default value would just make things more complex to understand.

So there are two solutions here:
- We somehow make possible to set a default in all cases, and use the presence of a default to decide whether a component should run or now
- We introduce some custom type that does nothing other than signaling Canals that the parameter doesn't need to be waited for. it's a shame that the name "optional" is already taken because that would be perfect :smile: Maybe `IsOptional`, or `HasDefault`.

I don't have a good answer right now, so feel free to suggest other approaches and ideas. I'll be thinking about this.

**Comment by MichelBartels** [comment]
Thanks for explaining this. However, I am not sure that I understand your explanation.
> because there are cases where setting a default is not possible (or quite awkward)

As far as I can see you already need to provide some default which is currently `None` in most cases. Otherwise, there will be an error about a missing parameter (e.g., what happened in my NAND example).

> while all other are waited for, regardless of whether a default is set or not

What's the point of setting a default then? If you need to provide them anyways, you guarantee that the default will be ignored.
